const ALBUMS=[
  {
    "id": "debut",
    "title": "Taylor Swift",
    "year": 2006,
    "version": "Deluxe Edition",
    "a": "#6eaaa5",
    "b": "#d8cba7",
    "tracks": [
      "Tim McGraw",
      "Picture to Burn",
      "Teardrops on My Guitar",
      "A Place in This World",
      "Cold as You",
      "The Outside",
      "Tied Together with a Smile",
      "Stay Beautiful",
      "Should've Said No",
      "Mary's Song (Oh My My My)",
      "Our Song",
      "I'm Only Me When I'm with You",
      "Invisible",
      "A Perfectly Good Heart",
      "Teardrops on My Guitar (Pop Version)"
    ]
  },
  {
    "id": "fearless",
    "title": "Fearless (Taylor’s Version)",
    "year": 2021,
    "version": "Taylor’s Version",
    "a": "#c69c5e",
    "b": "#e7d8b5",
    "tracks": [
      "Fearless",
      "Fifteen",
      "Love Story",
      "Hey Stephen",
      "White Horse",
      "You Belong with Me",
      "Breathe",
      "Tell Me Why",
      "You're Not Sorry",
      "The Way I Loved You",
      "Forever & Always",
      "The Best Day",
      "Change",
      "Jump Then Fall",
      "Untouchable",
      "Forever & Always (Piano Version)",
      "Come In with the Rain",
      "Superstar",
      "The Other Side of the Door",
      "Today Was a Fairytale",
      "You All Over Me",
      "Mr. Perfectly Fine",
      "We Were Happy",
      "That's When",
      "Don't You",
      "Bye Bye Baby"
    ]
  },
  {
    "id": "speak",
    "title": "Speak Now (Taylor’s Version)",
    "year": 2023,
    "version": "Taylor’s Version",
    "a": "#6d4779",
    "b": "#c8a1cb",
    "tracks": [
      "Mine",
      "Sparks Fly",
      "Back to December",
      "Speak Now",
      "Dear John",
      "Mean",
      "The Story of Us",
      "Never Grow Up",
      "Enchanted",
      "Better than Revenge",
      "Innocent",
      "Haunted",
      "Last Kiss",
      "Long Live",
      "Ours",
      "Superman",
      "Electric Touch",
      "When Emma Falls in Love",
      "I Can See You",
      "Castles Crumbling",
      "Foolish One",
      "Timeless"
    ]
  },
  {
    "id": "red",
    "title": "Red (Taylor’s Version)",
    "year": 2021,
    "version": "Taylor’s Version",
    "a": "#7e3030",
    "b": "#c78a65",
    "tracks": [
      "State of Grace",
      "Red",
      "Treacherous",
      "I Knew You Were Trouble",
      "All Too Well",
      "22",
      "I Almost Do",
      "We Are Never Ever Getting Back Together",
      "Stay Stay Stay",
      "The Last Time",
      "Holy Ground",
      "Sad Beautiful Tragic",
      "The Lucky One",
      "Everything Has Changed",
      "Starlight",
      "Begin Again",
      "The Moment I Knew",
      "Come Back… Be Here",
      "Girl at Home",
      "State of Grace (Acoustic Version)",
      "Ronan",
      "Better Man",
      "Nothing New",
      "Babe",
      "Message in a Bottle",
      "I Bet You Think About Me",
      "Forever Winter",
      "Run",
      "The Very First Night",
      "All Too Well (10 Minute Version)"
    ]
  },
  {
    "id": "1989",
    "title": "1989 (Taylor’s Version)",
    "year": 2023,
    "version": "Taylor’s Version [Deluxe]",
    "a": "#69a6c9",
    "b": "#d9c9aa",
    "tracks": [
      "Welcome to New York",
      "Blank Space",
      "Style",
      "Out of the Woods",
      "All You Had to Do Was Stay",
      "Shake It Off",
      "I Wish You Would",
      "Bad Blood",
      "Wildest Dreams",
      "How You Get the Girl",
      "This Love",
      "I Know Places",
      "Clean",
      "Wonderland",
      "You Are in Love",
      "New Romantics",
      "Slut!",
      "Say Don't Go",
      "Now That We Don't Talk",
      "Suburban Legends",
      "Is It Over Now?",
      "Bad Blood (feat. Kendrick Lamar)"
    ]
  },
  {
    "id": "reputation",
    "title": "reputation",
    "year": 2017,
    "version": "Original",
    "a": "#191919",
    "b": "#777777",
    "tracks": [
      "…Ready for It?",
      "End Game",
      "I Did Something Bad",
      "Don't Blame Me",
      "Delicate",
      "Look What You Made Me Do",
      "So It Goes…",
      "Gorgeous",
      "Getaway Car",
      "King of My Heart",
      "Dancing with Our Hands Tied",
      "Dress",
      "This Is Why We Can't Have Nice Things",
      "Call It What You Want",
      "New Year's Day"
    ]
  },
  {
    "id": "lover",
    "title": "Lover",
    "year": 2019,
    "version": "Original",
    "a": "#e790a9",
    "b": "#8fbcd0",
    "tracks": [
      "I Forgot That You Existed",
      "Cruel Summer",
      "Lover",
      "The Man",
      "The Archer",
      "I Think He Knows",
      "Miss Americana & the Heartbreak Prince",
      "Paper Rings",
      "Cornelia Street",
      "Death by a Thousand Cuts",
      "London Boy",
      "Soon You'll Get Better",
      "False God",
      "You Need to Calm Down",
      "Afterglow",
      "ME!",
      "It's Nice to Have a Friend",
      "Daylight"
    ]
  },
  {
    "id": "folklore",
    "title": "folklore",
    "year": 2020,
    "version": "deluxe version",
    "a": "#4d4d4d",
    "b": "#b8b8b8",
    "tracks": [
      "the 1",
      "cardigan",
      "the last great american dynasty",
      "exile",
      "my tears ricochet",
      "mirrorball",
      "seven",
      "august",
      "this is me trying",
      "illicit affairs",
      "invisible string",
      "mad woman",
      "epiphany",
      "betty",
      "peace",
      "hoax",
      "the lakes"
    ]
  },
  {
    "id": "evermore",
    "title": "evermore",
    "year": 2020,
    "version": "deluxe version",
    "a": "#6e3b28",
    "b": "#aa795c",
    "tracks": [
      "willow",
      "champagne problems",
      "gold rush",
      "'tis the damn season",
      "tolerate it",
      "no body, no crime",
      "happiness",
      "dorothea",
      "coney island",
      "ivy",
      "cowboy like me",
      "long story short",
      "marjorie",
      "closure",
      "evermore",
      "right where you left me",
      "it's time to go"
    ]
  },
  {
    "id": "midnights",
    "title": "Midnights",
    "year": 2022,
    "version": "The Til Dawn Edition",
    "a": "#25304d",
    "b": "#846d85",
    "tracks": [
      "Lavender Haze",
      "Maroon",
      "Anti-Hero",
      "Snow on the Beach",
      "You're on Your Own, Kid",
      "Midnight Rain",
      "Question...?",
      "Vigilante Shit",
      "Bejeweled",
      "Labyrinth",
      "Karma",
      "Sweet Nothing",
      "Mastermind",
      "The Great War",
      "Bigger Than the Whole Sky",
      "Paris",
      "High Infidelity",
      "Glitch",
      "Would've, Could've, Should've",
      "Dear Reader",
      "Hits Different",
      "Snow on the Beach (feat. More Lana Del Rey)",
      "Karma (feat. Ice Spice)"
    ]
  },
  {
    "id": "ttpd",
    "title": "THE TORTURED POETS DEPARTMENT",
    "year": 2024,
    "version": "THE ANTHOLOGY",
    "a": "#b5b0a8",
    "b": "#4b4844",
    "tracks": [
      "Fortnight",
      "The Tortured Poets Department",
      "My Boy Only Breaks His Favorite Toys",
      "Down Bad",
      "So Long, London",
      "But Daddy I Love Him",
      "Fresh Out the Slammer",
      "Florida!!!",
      "Guilty as Sin?",
      "Who's Afraid of Little Old Me?",
      "I Can Fix Him (No Really I Can)",
      "loml",
      "I Can Do It with a Broken Heart",
      "The Smallest Man Who Ever Lived",
      "The Alchemy",
      "Clara Bow",
      "The Black Dog",
      "imgonnagetyouback",
      "The Albatross",
      "Chloe or Sam or Sophia or Marcus",
      "How Did It End?",
      "So High School",
      "I Hate It Here",
      "thanK you aIMee",
      "I Look in People's Windows",
      "The Prophecy",
      "Cassandra",
      "Peter",
      "The Bolter",
      "Robin",
      "The Manuscript"
    ]
  },
  {
    "id": "showgirl",
    "title": "The Life of a Showgirl",
    "year": 2025,
    "version": "Original",
    "a": "#d26f42",
    "b": "#4f8090",
    "tracks": [
      "The Fate of Ophelia",
      "Elizabeth Taylor",
      "Opalite",
      "Father Figure",
      "Eldest Daughter",
      "Ruin the Friendship",
      "Actually Romantic",
      "Wi$h Li$t",
      "Wood",
      "CANCELLED!",
      "Honey",
      "The Life of a Showgirl (feat. Sabrina Carpenter)"
    ]
  }
];
const QUIZ=[
{q:'En quelle année Taylor Swift est-elle née ?',o:['1987','1988','1989','1990'],a:2,c:'Vie & personnalité'},
{q:'Quel album contient « Cruel Summer » ?',o:['reputation','Lover','folklore','Midnights'],a:1,c:'Discographie'},
{q:'Quel nombre est particulièrement associé à Taylor ?',o:['7','10','13','22'],a:2,c:'Fun facts'},
{q:'Quel album a été publié juste après folklore ?',o:['Midnights','evermore','Lover','Red (TV)'],a:1,c:'Chronologie'},
{q:'Quel album contient « august » ?',o:['folklore','evermore','Lover','1989'],a:0,c:'Discographie'},
{q:'Quel titre est une piste de Red (Taylor’s Version) ?',o:['cardigan','All Too Well','Delicate','Karma'],a:1,c:'Discographie'},
{q:'Comment s’appelle son frère ?',o:['Austin','Jack','Scott','Joe'],a:0,c:'Vie & personnalité'},
{q:'Quel album marque son virage pop pleinement assumé ?',o:['Fearless','Speak Now','1989','folklore'],a:2,c:'Carrière'},
{q:'Quel titre ouvre Midnights ?',o:['Anti-Hero','Lavender Haze','Maroon','Karma'],a:1,c:'Tracklists'},
{q:'Quel album contient « champagne problems » ?',o:['folklore','evermore','Midnights','Lover'],a:1,c:'Discographie'},
{q:'Quel album est sorti en 2017 ?',o:['Lover','reputation','1989','Red'],a:1,c:'Chronologie'},
{q:'Quel titre est associé à la piste 5 de Red ?',o:['22','All Too Well','Red','Treacherous'],a:1,c:'Tracklists'}
];